=== anvie/synpos/config/jpay.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Version: 1.0.0 http://www.synpos.com/jpay/jpay.dtd -->

<!--
     This is the DTD for synPOS payment gateways.  It defines
     the content necessary for all synPOS payment gateway entries in their XML file.  Please see the
     example XML files in the release as well as the synPOS documentation for details
     on how to create your own XML files that are valid for this DTD.
     @author H.Q. (hqi@baycloud.com)
     @since 1.0.0
-->

<!ELEMENT PaymentGateways (PaymentGateway)*>
<!ELEMENT PaymentGateway (GatewayId, GatewayName, GatewayClass, AcceptedCards)>
<!ELEMENT GatewayId (#PCDATA)>
<!ELEMENT GatewayName (#PCDATA)>
<!ELEMENT GatewayClass (ClassName, ClassParameter*)>
<!ELEMENT AcceptedCards (CreditCard?)>
<!ELEMENT ClassName (#PCDATA)>
<!ELEMENT ClassParameter (ParameterId, ParameterName, ParameterOption*)>
<!ELEMENT ParameterId (#PCDATA)>
<!ELEMENT ParameterName (#PCDATA)>
<!ELEMENT ParameterOption (OptionName, OptionValue)>
<!ELEMENT OptionName (#PCDATA)>
<!ELEMENT OptionValue (#PCDATA)>
<!ELEMENT CreditCard EMPTY>

=== anvie/synpos/config/jpay.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PaymentGateways PUBLIC "-//synPOS//DTD//EN"
                             "config/jpay.dtd">

<PaymentGateways>
  <PaymentGateway>
    <GatewayId>authorize</GatewayId>
    <GatewayName>Authorize.net</GatewayName>
    <GatewayClass>
    <ClassName>com.baycloud.synpos.payment.Authorize</ClassName>
    <ClassParameter>
      <ParameterId>url</ParameterId>
      <ParameterName>Gateway URL</ParameterName>
    </ClassParameter>
    <ClassParameter>
      <ParameterId>login</ParameterId>
      <ParameterName>Login</ParameterName>
    </ClassParameter>
    <ClassParameter>
      <ParameterId>transactionKey</ParameterId>
      <ParameterName>Transaction Key</ParameterName>
    </ClassParameter>
    <ClassParameter>
      <ParameterId>deviceType</ParameterId>
      <ParameterName>Device Type</ParameterName>
      <ParameterOption>
        <OptionName>Unknown</OptionName>
        <OptionValue>1</OptionValue>
      </ParameterOption>
      <ParameterOption>
        <OptionName>Unattended Terminal</OptionName>
        <OptionValue>2</OptionValue>
      </ParameterOption>
      <ParameterOption>
        <OptionName>Self Service Terminal</OptionName>
        <OptionValue>3</OptionValue>
      </ParameterOption>
      <ParameterOption>
        <OptionName>Electronic Cash Register</OptionName>
        <OptionValue>4</OptionValue>
      </ParameterOption>
      <ParameterOption>
        <OptionName>Personal Computer-Based Terminal</OptionName>
        <OptionValue>5</OptionValue>
      </ParameterOption>
      <ParameterOption>
        <OptionName>AirPay</OptionName>
        <OptionValue>6</OptionValue>
      </ParameterOption>
      <ParameterOption>
        <OptionName>Wireless POS</OptionName>
        <OptionValue>7</OptionValue>
      </ParameterOption>
      <ParameterOption>
        <OptionName>Website</OptionName>
        <OptionValue>8</OptionValue>
      </ParameterOption>
      <ParameterOption>
        <OptionName>Dial Terminal</OptionName>
        <OptionValue>9</OptionValue>
      </ParameterOption>
      <ParameterOption>
        <OptionName>Virtual Terminal</OptionName>
        <OptionValue>10</OptionValue>
      </ParameterOption>
    </ClassParameter>
    <ClassParameter>
      <ParameterId>transactionType</ParameterId>
      <ParameterName>Transaction Type</ParameterName>
      <ParameterOption>
        <OptionName>Authorize and Capture</OptionName>
        <OptionValue>AUTH_CAPTURE</OptionValue>
      </ParameterOption>
      <ParameterOption>
        <OptionName>Authorize Only</OptionName>
        <OptionValue>AUTH_ONLY</OptionValue>
      </ParameterOption>
    </ClassParameter>
    <ClassParameter>
      <ParameterId>testMode</ParameterId>
      <ParameterName>Test Mode</ParameterName>
      <ParameterOption>
        <OptionName></OptionName>
        <OptionValue>TRUE</OptionValue>
      </ParameterOption>
    </ClassParameter>
    </GatewayClass>
    <AcceptedCards>
      <CreditCard/>
    </AcceptedCards>
  </PaymentGateway>
</PaymentGateways>
